services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/templater:latest
    command: bash
    environment:
      GFW_TOKEN: $GFW_TOKEN
    volumes:
      - $PWD:/workdir

